// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfidbwbnovhllgzbhasc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmaWRid2Jub3ZobGxnemJoYXNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2MjgxNTgsImV4cCI6MjA4NjIwNDE1OH0.gKFk5_RLe3eKZAeW9NbHN_xr6IrYDflVFt3tl3abX7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});